# Site settings
title: All of Bayesian

email: "sunnybenlim@gmail.com"
url: "http://bayesian.github.io"
github_url: "http://github.com/sungbinlim/sl"
github_editurl: "/blob/gh-pages"
github_profile: "http://github.com/sungbinlim"
baseurl: "/sl"

exclude:
  - README.md
  - _site
  
highlighter: rouge
markdown: kramdown
plugins:
  - jemoji
  - jekyll-paginate

kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 4
paginate_path: /page:num

